repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: trailing-whitespace
        exclude: |
          (?x)^(.vimrc)$
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-json
        files: '\.\/*.json'
    -   id: pretty-format-json
        args: [--autofix, --indent=2, --no-ensure-ascii, --no-sort-keys]
