-   repo: local
    hooks:
    - id: sh_hook
      name: sh_hook
      entry: $HOME/.git-template/sh_hook
      description: Custom shell hook
      #types: [sh]
      language: script
      pass_filenames: false
      #files: ^file.*\.sh$
