#!/bin/sh
set -eEuo pipefail # Add < x > to args for stdout commands

version=1.3.0
DestDir=.cache

mkdir -p $DestDir && cd "$_"

if [ ! -f clj-zprint ]; then
  if [ "$(uname)" == "Darwin" ]; then
    curl -kfsSLJZO "https://github.com/kkinnear/zprint/releases/download/$version/zprintm-$version"
    mv zprintm-$version clj-zprint
    chmod 755 clj-zprint
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    curl -kfsSLJZO "https://github.com/kkinnear/zprint/releases/download/$version/zprintm-$version"
    mv zprintm-$version clj-zprint
    chmod 755 clj-zprint
  fi
fi

cd .. && \
  ls -la $DestDir && \
  file -I $DestDir/* | lolcat -f -t

  vim --cmd ':digraph | :quit ' -

#TODO
for file in $(git diff --name-only --diff-filter=ACM | grep -E '\.(clj)$')
do
  $DestDir/clj-zprint "{:search-config? true}"  < "$file" > "$file.out"
  mv "$file.out" "$file"
  $(git add "$file")
done
